//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
	using CapaEntidades;
	using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoRestauranteEntities : DbContext
    {
        public ProyectoRestauranteEntities()
            : base("name=ProyectoRestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Mesa> Mesas { get; set; }
        public DbSet<Reservacion> Reservaciones { get; set; }
    }
}
